<?php

return [
    'roles' => [
        'admin' => [
            'label' => 'Administrator',
            'menu'  => ['dashboard', 'sales', 'inventory', 'product', 'store', 'reports', 'users', 'settings'],
            'permissions' => [
                'dashboard.view'   => true,
                'analytics.sales'  => true,
                'analytics.inventory' => true,
                'analytics.product'=> true,
                'analytics.store'  => true,
                'reports.view'     => true,
                'reports.export'   => true,
                'crud.products'    => true,
                'crud.inventory'   => true,
                'crud.sales'       => true,
                'crud.stores'      => true,
                'crud.categories'  => true,
                'crud.users'       => true,
                'settings.view'    => true,
            ],
        ],
        'manager' => [
            'label' => 'Manager',
            'menu'  => ['dashboard', 'sales', 'product', 'store', 'reports'],
            'permissions' => [
                'dashboard.view'   => true,
                'analytics.sales'  => true,
                'analytics.inventory' => true,
                'analytics.product'=> true,
                'analytics.store'  => true,
                'reports.view'     => true,
                'reports.export'   => true,
                'crud.products'    => false,
                'crud.inventory'   => false,
                'crud.sales'       => false,
                'crud.stores'      => false,
                'crud.categories'  => false,
                'crud.users'       => false,
                'settings.view'    => false,
            ],
        ],
        'sales' => [
            'label' => 'Sales Staff',
            'menu'  => ['dashboard', 'sales_crud', 'orders', 'products_view', 'sales', 'product'],
            'permissions' => [
                'dashboard.view'   => true,
                'analytics.sales'  => true,
                'analytics.inventory' => false,
                'analytics.product'=> true,
                'analytics.store'  => false,
                'reports.view'     => false,
                'reports.export'   => false,
                'crud.products'    => 'view',
                'crud.inventory'   => false,
                'crud.sales'       => true,
                'crud.stores'      => false,
                'crud.categories'  => false,
                'crud.users'       => false,
                'settings.view'    => false,
            ],
        ],
        'warehouse' => [
            'label' => 'Warehouse Staff',
            'menu'  => ['dashboard', 'inventory_crud', 'stock_monitor'],
            'permissions' => [
                'dashboard.view'   => true,
                'analytics.sales'  => false,
                'analytics.inventory' => true,
                'analytics.product'=> false,
                'analytics.store'  => false,
                'reports.view'     => false,
                'reports.export'   => false,
                'crud.products'    => false,
                'crud.inventory'   => true,
                'crud.sales'       => false,
                'crud.stores'      => false,
                'crud.categories'  => false,
                'crud.users'       => false,
                'settings.view'    => false,
            ],
        ],
    ],
];
